language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

env:
  - COMPOSER_FLAGS=""
  - COMPOSER_FLAGS="--prefer-lowest"

sudo: false

matrix:
  allow_failures:
    - php: 7.0
    - php: hhvm

before_script:
  - composer update --prefer-source ${COMPOSER_FLAGS}

script: ./bin/phpspec run -f pretty
