language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1

env:
  - COMPOSER_FLAGS=""
  - COMPOSER_FLAGS="--prefer-lowest"

sudo: false

before_script:
  - phpenv config-rm xdebug.ini || true # TODO: remove once xdebug for 7.1 is officially supported on travis
  - composer self-update -n
  - composer update --prefer-source ${COMPOSER_FLAGS}

script: ./bin/phpspec run -f pretty
