language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0

sudo: false

matrix:
  allow_failures:
    - php: 7.0

before_script:
  - composer --prefer-source --dev install

script: ./bin/phpspec run -f pretty
