language: php

matrix:
  include:
    - php: 7.1
      env:
        - COMPOSER_FLAGS='--prefer-lowest'
    - php: 7.1

sudo: false

before_script:
  - phpenv config-rm xdebug.ini
  - composer update $COMPOSER_FLAGS

script: ./bin/phpspec run -f pretty
